Django_social/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),

    path('', include(('posts.urls', 'posts'), namespace='posts')),

    path('users/', include(('users.urls', 'users'), namespace='users'))

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
"""Post URLs"""

# Django

from django.urls import path

# views
from posts.views import PostsFeedView, DetailView, new_post

urlpatterns = [
    path(
        route='',
        view=PostsFeedView.as_view(),
        name='feed'
    ),
    path(
        route='posts/new/',
        view=new_post,
        name='new_post'
    ),
    path(
        route='post/<int:pk>',
        view=DetailView.as_view(),
        name='detail'
    )
]

users/urls.py
"""User views"""

# Django
from django.urls import path


# views
from users import views

urlpatterns = [

    path(
        route='profile/<str:username>/',
        view=views.DetailUser.as_view(template_name='users/detail.html'),
        name='detail'
    ),
    path(
        route='login/',
        view=views.login_view,
        name='login'
    ),
    path(
        route='logout/',
        view=views.logout_view,
        name='logout'
    ),
    path(
        route='signup/',
        view=views.signup_view,
        name='signup'
    ),
    path(
        route='me/update_profile/',
        view=views.update_profile,
        name='update'
    )
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    {% block head_content %}
    {% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
</head>

<body>
    {% include "nav.html" %}
    <div class="container mt-5 pt-5">
        {% block container %}
        {% endblock %}
    </div>
</body>
<footer>






</footer>
</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg sticky-top" id="main-navbar">
    <div class="container">

        <a class="navbar-brand pr-5" style='border-right: 1px solid #efefef;' href="{% url 'posts:feed' %}">
            <img src="{% static 'img/asimetrix.png' %}" height="45" class="d-inline-block align-top"/>
        </a>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a href=" {% url 'users:detail' username=request.user.username %}">
                        {%if user.profile.picture %}
                        <img src="{{ user.profile.picture.url}}" class="rounded-circle" height="50"/>
                        {% else %}
                        <img src="{% static 'img/default-profile.png' %}" height="35" class="d-inline-block align-top rounded-circle"/>
                        {% endif %}
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href=" {% url 'posts:new_post' %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'users:logout' %}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>