Django_social/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),

    path('', include(('posts.urls', 'posts'), namespace='posts')),

    path('users/', include(('users.urls', 'users'), namespace='users'))

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
"""Post URLs"""

# Django

from django.urls import path

# views
from posts.views import PostsFeedView, DetailView, new_post

urlpatterns = [
    path(
        route='',
        view=PostsFeedView.as_view(),
        name='feed'
    ),
    path(
        route='posts/new/',
        view=new_post,
        name='new_post'
    ),
    path(
        route='post/<int:pk>',
        view=DetailView.as_view(),
        name='detail'
    )
]

users/urls.py
"""User views"""

# Django
from django.urls import path


# views
from users import views

urlpatterns = [

    path(
        route='profile/<str:username>/',
        view=views.DetailUser.as_view(template_name='users/detail.html'),
        name='detail'
    ),
    path(
        route='login/',
        view=views.login_view,
        name='login'
    ),
    path(
        route='logout/',
        view=views.logout_view,
        name='logout'
    ),
    path(
        route='signup/',
        view=views.signup_view,
        name='signup'
    ),
    path(
        route='me/update_profile/',
        view=views.update_profile,
        name='update'
    )
]

users/models.py
""""Users models"""
from django.db import models
from django.contrib.auth.models import User, AbstractUser

# Create your models here.



class Profile(models.Model):
    """Profile model.
    Proxy model that extends the base data with other information"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(max_length=200,blank=True)
    biography = models.TextField(blank=True)

    phone_number = models.CharField(max_length=20)

    picture = models.ImageField(
        upload_to='./users/pictures',
        blank=True,
        null=True
    )
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

users/forms.py
"""User forms"""

from django import forms
from django.contrib.auth.models import User

# Models
from users.models import Profile


class SignupForm(forms.Form):
    username = forms.CharField(min_length=4, max_length=50)
    password = forms.CharField(max_length=50, widget=forms.PasswordInput())
    password_confirmation = forms.CharField(max_length=70, widget=forms.PasswordInput())

    first_name = forms.CharField(min_length=2, max_length=50)
    last_name = forms.CharField(min_length=2, max_length=50)

    email = forms.EmailField(min_length=6, max_length=50, widget=forms.EmailInput())

    def clean_username(self):
        """Username must be unique"""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username already in use.')
        return username

    def clean_email(self):
        """Email must be unique"""
        email = self.cleaned_data['email']
        email_taken = User.objects.filter(email=email).exists()
        if email_taken:
            raise forms.ValidationError('Email already exists')
        return email

    def clean(self):
        """Validation password and password confirmation matching"""
        data = super().clean()
        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError(' Passwords do not macth')
        return data

    def save(self):
        """Create user and profile"""
        data = self.cleaned_data
        data.pop('password_confirmation')
        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()


class ProfileForms(forms.Form):
    website = forms.URLField(max_length=200)
    biography = forms.CharField(max_length=500, required=True)
    phone_number = forms.CharField(max_length=20, required=True)
    picture = forms.ImageField()

users/views.py
"""User's views"""

# Django
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView
from django.urls import reverse

# models
from django.contrib.auth.models import User
from users.forms import ProfileForms, SignupForm
from posts.models import Post

#settings
User._meta.get_field('email')._unique = True


# class views

class DetailUser(LoginRequiredMixin, DetailView):
    template_name = 'users/detail.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    queryset = User.objects.all()
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        """Add posts to context"""
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['posts'] = Post.objects.filter(user=user).order_by('-created')
        return context


# Create your views here.
@login_required
def update_profile(request):
    """ update a user's profile"""
    profile = request.user.profile

    if request.method == 'POST':
        form = ProfileForms(request.POST, request.FILES)
        if form.is_valid():
            data = form.cleaned_data
            profile.website = data['website']
            profile.phone_number = data['phone_number']
            profile.biography = data['biography']
            profile.picture = data['picture']
            profile.save()

            url = reverse('users:update', kwargs={
                'username': request.user.username
            })
            return redirect(url)
    else:
        form = ProfileForms()

    return render(request, template_name='users/update_profile.html', context={
        'profile': profile,
        'user': request.user,
        'form': form
    })


def login_view(request):
    """Login view"""
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect('posts:feed')
        else:
            return render(request, 'users/login.html', {'error': 'Invalid username or password'})
    return render(request, 'users/login.html')


@login_required
def logout_view(request):
    """Logout a user"""
    logout(request)
    return redirect('users:login')


def signup_view(request):
    """Sign up a user"""

    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:login')
    else:
        form = SignupForm()
    return render(
        request,
        template_name='users/signup.html',
        context={
            'form': form
        }
    )

templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
</head>
<body class="h-100">
    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">
                <img src="{% static 'img/asimetrix.png' %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">

                {% block container %}
                {% endblock%}
            </div>
        </div>
    </div>
</body>
</html>

templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ user.username }} | Platzigram</title>
{% endblock %}

{% block container %}

    <div class="container mb-5" style="margin-top: 8em;">
        <div class="row">
            <div class="col-sm-4 d-flex justify-content-center">
                <img
                        src="{{ user.profile.picture.url }}"
                        alt="@{{ user.username}}"
                        class="rounded-circle"
                        width="150px" />
            </div>
            <div class="col-sm-8">

                <h2 style="font-weight: 100;">

                    {{ request.user.username }}

                    {% if request.user == user %}
                        <a href="{% url 'users:update' %}"
                            class="ml-5 btn btn-sm btn-outline-info"
                        >
                            Edit profile
                        </a>
                    {% else %}
                        <a
                            href=""
                            class="ml-5 btn btn-sm btn-primary"
                        >
                            Follow
                        </a>
                    {% endif %}
                </h2>
                <div class="row mt-2" style="font-size: 1.2em">
                    <div class="col-sm-4">
                        <b>{{ user.profile.posts_count }}785</b> posts
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.followers }}1,401</b> followers
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.following }}491</b> following
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-sm-12">
                        <p>{{ user.profile.biography }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr>
    <div class="container" id="user-posts">
        <div class="row mt-3">
            {% for post in posts %}
            <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
                <a href="{% url 'posts:detail' post.pk %}" class="border">
                    <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid"/>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/users/login.html
{% extends "users/base.html" %}

{% block head_content %}
    <title>Plaztigram sign in</title>
{% endblock %}

{% block container %}

    {% if error %}
        <p class="alert alert-danger">{{ error }} </p>
    {% endif %}

    <form method="POST" action='{% url "users:login" %}'>
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control mb-2" type="text" placeholder="Username" name="username" />
        </div>

            <input class="form-control mb-2" type="password" placeholder="Password" name="password" />

        <div>
        <button class="btn btn-primary btn-block mb-2" type="submit">Sign in!</button>
        </div>

    </form>

        <a href='{% url "users:signup" %}' class="btn btn-secondary btn-block mt-2" >Sign up!</a>

{% endblock %}

templates/users/signup.html
{% extends "users/base.html" %}

{% block head_content %}
<title>Platzigram sign up</title>
{% endblock %}

{% block container %}

    {% if error %}
        <p class="alert alert-danger">{{ error }}</p>
    {% endif %}

    <form action="{% url 'users:signup' %}" method="POST">
        {% csrf_token %}

        <div class="form-group">
            <input class="form-control {% if form.username.errors %} is-invalid {% endif %}"
                   type="text"
                   placeholder="Username"
                   name="username"
                   value="{% if form.errors %}{{form.username.value}}{% else %}{{placeholder}}{% endif %}"
                   required="true"
            />
            <div class="invalid-feedback">
                {% for error in form.username.errors %}
                {{error}}
                {% endfor %}
            </div>
        </div>

        <div class="form-group">
            <input class="form-control {% if form.password.errors %} is-invalid {% endif %}"
                   type="password"
                   placeholder="Password"
                   name="password"
                   required="true" />
            <div class="invalid-feedback">
                {% for error in form.password.errors %}
                {{error}}
                {% endfor %}
            </div>
        </div>

        <div class="form-group">
            <input class="form-control {% if form.password_confirmation.errors %} is-invalid {% endif %}"
                   type="password"
                   placeholder="Password confirmation"
                   name="password_confirmation"
                   required="true" />
            <div class="invalid-feedback">
                {% for error in form.password_confirmation.errors %}
                {{error}}
                {% endfor %}
            </div>
        </div>

        <div class="form-group">
            <input class="form-control"
                   type="text"
                   placeholder="First name"
                   name="first_name"
                   value="{% if form.errors %} {{form.first_name.value}} {% else %}{{placeholder}}{% endif %}"
                   required="true" />
            <div class="invalid-feedback">
                {% for error in form.first_name.errors %}
                {{error}}
                {% endfor %}
            </div>
        </div>

        <div class="form-group">
            <input class="form-control"
                   type="text"
                   placeholder="Last name"
                   name="last_name"
                   value="{% if form.errors %} {{form.last_name.value}} {% else %}{{placeholder}}{% endif %}"
                   required="true" />
            <div class="invalid-feedback">
                {% for error in form.last_name.errors %}
                {{error}}
                {% endfor %}
            </div>
        </div>

        <div class="form-group">
            <input class="form-control {% if form.email.errors %} is-invalid {% endif %}"
                   type="email"
                   placeholder="Email address"
                   name="email"
                   value="{% if form.errors %} {{form.email.value}} {% else %} {{placeholder}} {% endif %}"
                   required="true" />
            <div class="invalid-feedback">
                {% for error in form.email.errors %}
                {{error}}
                {% endfor %}
            </div>
        </div>

        <button class="btn btn-primary btn-block mt-5" type="submit">Register!</button>

    </form>

    <div>



    </div>

{% endblock %}

templates/users/update_profile.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>@{{ request.user.username }} | Update profiles</title>
{% endblock %}

{% block container %}

<div class="container">

    <div class="row justify-content-md-center">
        <div class="col-6 p-4" id="profile-box">

            <form action="{% url 'users:update' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}


                <div class='media'>
                    {%if profile.picture %}
                        <img src="{{ profile.picture.url }}" class="rounded-circle" height="50"/>
                    {% else %}
                        <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50"/>
                    {% endif %}

                    <div class="media-body">
                        <h5 class="ml-4"> @{{ user.username }} | {{ user.get_full_name }} </h5>
                        <p class="ml-4">
                            <input type="file" name="picture" ></p>
                    </div>
                </div>

                {% for error in form.picture.errors %}
                <div class="alert alert-danger">
                    <b>Picture: </b>{{error}}
                 </div>
                {% endfor %}


                <hr><br>

                <div class="form-group">
                    <label>Website</label>
                    <input class="form-control {% if form.website.errors %} is-invalid {% endif %}"
                            type="text"
                            name="website"
                            placeholder="Website"
                            value="{% if form.errors %} {{form.website.value}} {% else %} {{ profile.website }} {% endif %}"
                            />
                          <div class="invalid-feedback">
                            {% for error in form.website.errors %}
                            {{error}}
                            {% endfor %}
                          </div>
                </div>

                <div class="form-group">
                    <label>Biography</label>
                    {#si ocurre un error lo muestra#}
                    <textarea
                    class="form-control {% if form.biography.errors %} is-invalid {% endif %}"
                    name="biography"
                    value=" {% if form.errors %} {{form.biography.value}} {% else %} {{profile.biography}} {% endif %}">
                    </textarea>

                    <div class="invalid-feedback">
                        {% for error in form.biography.errors %}
                            {{error}}
                        {% endfor %}
                      </div>
                </div>

                <div class="form-group">
                    <label>Phone number</label>
                    <input
                        class="form-control {% if form.phone_number.errors %} is-invalid {% endif %}"
                        type="text"
                        name="phone_number"
                        {% if form.errors %} {{ form.phone_number.value }} {% else %} {{ profile.phone_number }} {% endif %}
                        placeholder="Phone number"
                        value="{{ profile.phone_number }}"
                    />
                    <div class="invalid-feedback">
                        {% for error in form.phone_number.errors %}
                        {{error}}
                        {% endfor %}
                      </div>
              </div>

                <button type="submit" class="btn btn-primary btn-block mt-5">Update info</button>
            </form>


        </div>
    </div>
</div>
{% endblock %}